
project1:
  outputs:

    dev:
      type: mysql
      threads: 1
      host: localhost
      port: 3306
      username : root
      password: root
      schema: analytics
    
    prod:
      type: mysql
      threads: 1
      host: localhost
      port: 3306
      username : root
      password: root
      schema: analytics

    stag:
      type: mysql
      threads: 1
      host: localhost
      port: 3306
      username : root
      password: root
      schema: analytics
  
  target: dev


project1_postgres:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      username : root
      password: root
      schema: analytics
    
    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      username : root
      password: root
      schema: analytics

    stag:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      username : root
      password: root
      schema: analytics
  
  target: dev