CREATE TABLE IF NOT EXISTS `sensor_data` 
(
    `timeperiod` VARCHAR(100) NOT NULL,
    `flow1` FLOAT DEFAULT NULL,
    `occupancy1` FLOAT DEFAULT NULL,
    `speed1` FLOAT DEFAULT NULL,
    `flow2` FLOAT DEFAULT NULL,
    `occupancy2` FLOAT DEFAULT NULL,
    `speed2` FLOAT DEFAULT NULL,
    `flow3` FLOAT DEFAULT NULL,
    `occupancy3` FLOAT DEFAULT NULL,
    `speed3` FLOAT DEFAULT NULL,
    `flow4` FLOAT DEFAULT NULL,
    `occupancy4` FLOAT DEFAULT NULL,
    `speed4` FLOAT DEFAULT NULL,
    `flow5` FLOAT DEFAULT NULL,
    `occupancy5` FLOAT DEFAULT NULL,
    `speed5` FLOAT DEFAULT NULL,
    `flow6` FLOAT DEFAULT NULL,
    `occupancy6` FLOAT DEFAULT NULL,
    `speed6` FLOAT DEFAULT NULL,
    `flow7` FLOAT DEFAULT NULL,
    `occupancy7` FLOAT DEFAULT NULL,
    `speed7` FLOAT DEFAULT NULL,
    `flow8` FLOAT DEFAULT NULL,
    `occupancy8` FLOAT DEFAULT NULL,
    `speed8` FLOAT DEFAULT NULL
);
